version: '3.5'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat-network

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    restart: always
    deploy:
      replicas: 3 
    ports:
      - "3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/chat
      - REDIS_URL=redis://redis:6379
      - REDIS_TTL=3600 
      - SESSION_SECRET=af2693b7-a522-4979-9e7b-a3c4d963a210
    networks:
      - chat-network

  chat-client:
    build:
      context: ./chat-client
      dockerfile: Dockerfile
    container_name: chat-client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - nginx
    environment:
      - NEXT_PUBLIC_API_URL=http://nginx/api
    networks:
      - chat-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chat-server
    networks:
      - chat-network

volumes:
  mongodb_data:

networks:
  chat-network:
