import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";

import { AuthProvider, ReactQueryProvider } from "@app/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AntdRegistry>
            <AuthProvider>{children}</AuthProvider>
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
